os: linux
dist: xenial
language: python
python: "3.7"
services:
  - docker
env:
  CONAN_GCC_VERSIONS=8
  CONAN_DOCKER_IMAGE=conanio/gcc8
  CONAN_USERNAME=ezored
  CONAN_REMOTES=https://api.bintray.com/conan/bincrafters/public-conan
  CONAN_REFERENCE=ezored/latest@ezored/stable

install:
  - pip install conan_package_tools
  - pip install conan
  - conan user
script:
  - python build.py
